### ISSUE TITLE
Index out of bounds in Speck6496KeySchedule

### ISSUE THREAD

**Issue by robertguetzkow** [iadgov/simon-speck#1]
It appears that the Speck6496KeySchedule as shown in the implementation guide tries to save a round key at an index that is out of bounds. This version of the Speck cipher has 26 rounds, which requires equally many round keys. The key schedules last assignment `rk[i]=A;` is for index 26, the 27th round key. 
This instruction shouldn't be there, all required round keys have already been generated.

Version from the "SIMON and SPECK Implementation Guide" [0]:
```
void Speck6496KeySchedule(u32 K[],u32 rk[])
{
    u32 i,C=K[2],B=K[1],A=K[0];
    for(i=0;i<26;){
        rk[i]=A; ER32(B,A,i++);
        rk[i]=A; ER32(C,A,i++);
    }
    rk[i]=A;
}
```

Fixed version:
```
void Speck6496KeySchedule(u32 K[],u32 rk[])
{
    u32 i,C=K[2],B=K[1],A=K[0];
    for(i=0;i<26;){
        rk[i]=A; ER32(B,A,i++);
        rk[i]=A; ER32(C,A,i++);
    }
}
```

[0] R. Beaulieu, D. Shors, J. Smith, S. Treatman-Clark, B. Weeks and L. Wingers,
    "SIMON and SPECK Implementation Guide", NSA Cybersecurity, June 26, 2018. [Online].
    Available: https://nsacyber.github.io/simon-speck/implementations/ImplementationGuide1.1.pdf

**Comment by robertguetzkow** [comment]
The reference implementation is correct.

https://github.com/nsacyber/simon-speck-supercop/blob/5bba85c3094029eb73b7077441e5c6ea2f2cb1c6/crypto_stream/speck6496ctr/ref/stream.c#L123-L133

**Comment by beweeks** [comment]
Modified the SPECK6496 code in the reference guide to remove the last rk[i]=A as robertguetzkow has pointed out. Changed the reference link in the original comment for the new version of the paper as well. Thanks robertguetzkow!
